# Generated by Django 5.2 on 2025-04-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='answers',
            field=models.JSONField(default=dict),
        ),
    ]
